export const SET_SIGN_IN_LOADER = 'SET_SIGN_IN_LOADER';
export const SET_SIGN_UP_LOADER = 'SET_SIGN_UP_LOADER';
export const SET_VERIFY_CODE_LOADER = 'SET_VERIFY_CODE_LOADER';
export const SET_SEND_VERIFY_CODE_LOADER = 'SET_SEND_VERIFY_CODE_LOADER';
export const SET_RE_SEND_VERIFY_CODE_LOADER = 'SET_RE_SEND_VERIFY_CODE_LOADER';
export const SET_FORGET_PASSWORD_LOADER = 'SET_FORGET_PASSWORD_LOADER';
export const SET_PASSWORD_LOADER = 'SET_PASSWORD_LOADER';
